# Generated by Django 3.2.8 on 2022-10-03 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_m', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoproject',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todoproject',
            name='date_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
